declare -a App_Install=(
	"wine:	wine"
	"flatpak:	flatpak"
	"snap:	snapd"
	"7_zip:	p7-zipfull"
	"adwaita_theme:	adwaita-icon-theme"
	"audacity:	audacity"
	"backup_tool:	mintbackup"
	"biglybt:	biglybt default-jre libgtk-3-dev libswt-gtk-4-java"
	"brave:	brave-browser apt-transport-https curl"
	"bleachbit:	bleachbit"
	"bluetooth:	linux-firmware pipewire pipewire-pulse pipewire-audio-client-libraries libspa-0.2-bluetooth"
	"bulky:	bulky"
	"calibre:	calibre"
	"celluloid:	celluloid"
	"disk_usage_analyzer:	baobab"
	"disks:	gnome-disk-utility"
	"docker:	docker-ce docker-ce-cli containerd.io docker-compose-plugin"
	"drawing:	drawing"
	"dropbox:	dropbox"
	"eye_of_gnome:	eog"
	"fail2ban:	fail2ban"
	"filezilla:	filezilla"
	"fingerprints:	fingwit"
	"firefox:	firefox"
	"font_dejavu:	fonts-dejavu"
	"git:	git"
	"gimp:	gimp"
	"gnome_calculator:	gnome-calculator"
	"gnome_calendar:	gnome-calendar"
	"gnome_power_manager:	gnome-power-manager "
	"gnome_screenshot:	gnome-screenshot"
	"gnome_terminal:	gnome-terminal"
	"google_chrome:	google-chrome"
	"gramps:	gramps"
	"handbrake:	handbrake"
	"hypnotix:	hypnotix"
	"image_viewer:	xviewer"
	"jq:	jq"
	"kcalc:	kcalc"
	"keepass:	keepass2"
	"keepassxc:	keepassxc"
	"kleopatra:	kleopatra"
	"krita:	krita"
	"libreoffice:	libreoffice"
	"librewolf:	librewolf"
	"megasync:	megasync"
	"mintchat:	mintchat"
	"mousepad:	mousepad"
	"mpv_Media_player:	mpv"
	"mtpaint:	mtpaint"
	"mullvad_browser:	mullvad-browser"
	"mullvad_VPN:	mullvad-vpn"
	"mypaint:	mypaint"
	"nautilus:	nautilus"
	"ncdu:	ncdu"
	"nomacs:	nomacs"
	"notepadqq:	notepadqq"
	"numlockx:	numlockx"
	"obs_studio:	obs-studio"
	"onboard:	onboard"
	"online_accounts:	gnome-online-accounts-gtk"
	"pidgin:	pidgin"
	"pix:	pix"
	"qbittorrent:	qbittorrent"
	"qemu:	qemu-system"
	"rhythmbox:	rhythmbox"
	"scrcpy:	scrcpy"
	"seahorse:	seahorse"
	"signal:	signal-desktop"
	"smplayer:	smplayer"
	"steam:	steam"
	"sticky:	sticky"
	"torbrowser:	torbrowser-launcher"
	"thunderbird:	thunderbird"
	"tigervnc:	tigervnc-viewer" #check if its the good one
	"ufw:	ufw"
	"vim:	vim"
	"virt_viewer:	virt-viewer virtualbox-guest-additions-iso"
	"virtualbox:	virtualbox virtualbox-guest-additions-iso"
	"vlc:	vlc"
	"vuze:	vuze"
	"winboat:	" #later adding packages
	"wire:	wire-desktop apt-transport-https"
	"xdotool:	xdotool"
	"xed:	xed"
	"xreader:	xreader"
)
#android emulater