declare -a App_Install=(
	"wine:	wine"
	"flatpak:	flatpak"
	"snap:	snapd"
	#"keyrings:	libsecret-1-0 libsecret-1-dev gnome-keyring"
	"7_zip:	p7zip-full"
	"adwaita_theme:	adwaita-icon-theme"
	"audacity:	audacity"
	"backup_tool:	mintbackup"
	#"biglybt:	biglybt default-jre libgtk-3-dev libswt-gtk-4-java" #ai local asking if better to set it in flatpak
	"brave:	brave-browser curl"
	"bleachbit:	bleachbit"
	"bluetooth:	blueman bluetooth bluez bluez-tools linux-firmware pipewire pipewire-pulse pipewire-audio-client-libraries libspa-0.2-bluetooth"
	"bulky:	bulky"
	"btop:	btop"
	"calibre:	calibre"
	"celluloid:	celluloid"
	"disk_usage_analyzer:	baobab"
	"disks:	gnome-disk-utility"
	"docker:	docker-ce docker-ce-cli containerd.io docker-compose-plugin"
	"drawing:	drawing"
	"dropbox:	dropbox"
	"element:	element-desktop"
	"eye_of_gnome:	eog"
	"fail2ban:	fail2ban"
	"filezilla:	filezilla"
	"fingerprints:	fingwit"
	"firefox:	firefox"
	"flameshot:	flameshot"
	"font_dejavu:	fonts-dejavu"
	"gawk:	gawk"
	"git:	git"
	"gimp:	gimp"
	"gnome_calculator:	gnome-calculator"
	"gnome_calendar:	gnome-calendar"
	"gnome_power_manager:	gnome-power-manager "
	"gnome_screenshot:	gnome-screenshot"
	"gnome_system_monitor:	gnome-system-monitor"
	"gnome_terminal:	gnome-terminal"
	#"google_chrome:	google-chrome"
	"gramps:	gramps"
	"gthumb:	gthumb"
	"handbrake:	handbrake"
	"hp_printer:	hplip"
	"hypnotix:	hypnotix"
	"image_viewer:	xviewer"
	"jq:	jq"
	"kcalc:	kcalc"
	"keepass:	keepass2"
	"keepassxc:	keepassxc"
	"kleopatra:	kleopatra scdaemon"
	"krita:	krita"
	"libreoffice:	libreoffice"
	"librewolf:	librewolf"
	"megasync:	megasync"
	"minecraft_server:	openjdk-21-jre-headless openjdk-21-jdk-headless" #java maby not needed anymore
	"mintchat:	mintchat"
	"mousepad:	mousepad"
	"mpv_Media_player:	mpv"
	"mtpaint:	mtpaint"
	"mullvad_browser:	mullvad-browser"
	"mullvad_VPN:	mullvad-vpn"
	"mypaint:	mypaint"
	"nautilus:	nautilus"
	"ncdu:	ncdu"
	"nomacs:	nomacs"
	"notepadqq:	notepadqq"
	"numlockx:	numlockx"
	"obs_studio:	obs-studio"
	"onboard:	onboard"
	"online_accounts:	gnome-online-accounts-gtk"
	"pidgin:	pidgin"
	"pix:	pix"
	"qbittorrent:	qbittorrent"
	"qemu:	qemu-kvm libvirt-daemon-system libvirt-clients virt-viewer"
	"rhythmbox:	rhythmbox"
	"scrcpy:	scrcpy"
	"seahorse:	seahorse"
	"shutter:	shutter"
	"spectacle:	spectacle"
	#"signal:	signal-desktop"
	"smplayer:	smplayer"
	"software_manager:	mintinstall"
	"steam:	steam"
	"sticky:	sticky"
	"thunar:	thunar"
	"thunderbird:	thunderbird"
	"tigervnc:	tigervnc-viewer"
	"torbrowser:	torbrowser-launcher"
	"transmission:	transmission-gtk"
	"ufw:	ufw"
	"vim:	vim"
	"virt_viewer:	virt-viewer virtualbox-guest-additions-iso"
	"virtualbox:	virtualbox virtualbox-guest-additions-iso"
	"vivaldi:	vivaldi-stable"
	"vlc:	vlc"
	"vuze:	vuze"
	"warpinator:	warpinator"
	"waydroid:	waydroid weston curl ca-certificates lxc lxc-utils python3-lxc"
	"web_apps:	webapp-manager"
	#"winboat:	" #later adding packages
	#"wire:	wire-desktop apt-transport-https"
	"xdotool:	xdotool"
	"xed:	xed"
	"xreader:	xreader"
)